const express = require('express')
const { newOrder } = require('../controllers/order_controller/createNewOrder')
const { myOrders } = require('../controllers/order_controller/myOrders')
const { getSingleOrder } = require('../controllers/order_controller/getSingleOrder')
const { auth, authorizedRole } = require('../middleware/authorize')
const { mySingleOrder } = require('../controllers/order_controller/mySingleOrder')
const { getAllOrders } = require('../controllers/order_controller/getAllOrders')
const { updateOrderStatus } = require('../controllers/order_controller/updateOrderStatus')
const { deleteOrder } = require('../controllers/order_controller/deleteOrder')
const { newOrderUnknownUser } = require('../controllers/order_controller/createNewOrderUnknownUser')
const { unknownUserSingleOrder } = require('../controllers/order_controller/unknownUserOrder')
const {unknownUserSingleOrder2} = require('../controllers/order_controller/unknownUserOrder2')
const router = new express.Router()

router.post('/order/new', auth, newOrder)
router.post('/order/unknown-user', newOrderUnknownUser)
router.get('/admin/order/:id',  auth, authorizedRole('admin'), getSingleOrder )
router.get('/orders/me', auth, myOrders)
router.get('/order/me/:id', auth, mySingleOrder)
router.get('/unknown-user-order/:id', unknownUserSingleOrder)
router.post('/unknown-user-order/:id', unknownUserSingleOrder2)
router.get('/admin/orders', auth, authorizedRole('admin'), getAllOrders)
router.put('/admin/order/:id', auth, authorizedRole('admin'), updateOrderStatus)
router.delete('/admin/order/:id', auth, authorizedRole('admin'), deleteOrder )
module.exports = router