const express = require('express')
const { auth, authorizedRole } = require('../middleware/authorize')
const {signUpUser} = require('../controllers/user_controller/siguUpUser')
const {loginUser} = require('../controllers/user_controller/loginUser')
const {logoutUser} = require('../controllers/user_controller/logoutUser')
const {logoutAll} = require('../controllers/user_controller/logoutAll')
const {forgotPassword} = require('../controllers/user_controller/forgotPassword')
const {resetPassword} = require('../controllers/user_controller/resetPassword')
const {getUserDetails} = require('../controllers/user_controller/getUserDetails')
const {updatePassword} = require('../controllers/user_controller/updatePassword')
const {updateProfile} = require('../controllers/user_controller/updateProfile')
const {getAllUsers} = require('../controllers/admin_controller/getAllUsers')
const {getSingleUser} = require('../controllers/admin_controller/getSingleUser')
const {updateUserRole} = require('../controllers/admin_controller/updateUserRole')
const {deleteUser} = require('../controllers/admin_controller/deleteUser')
const {updateAddress} = require('../controllers/user_controller/updateAddress')
const router = new express.Router()

router.post('/users/signup', signUpUser)
router.post('/users/login', loginUser)
router.get('/users/logout', auth, logoutUser)
router.post('/users/logoutAll', auth, logoutAll)
router.post('/users/password/forgot', forgotPassword),
router.put('/password/reset/:token', resetPassword)
router.get('/users/me', auth, getUserDetails)
router.put('/users/password/update', auth, updatePassword)
router.put('/update/me', auth, updateProfile)
router.put('/address/update', auth, updateAddress)
router.get('/admin/users/all', auth, authorizedRole('admin'), getAllUsers)
router.get('/admin/users/:id', auth, authorizedRole('admin'), getSingleUser)
router.put('/admin/users/:id', auth, authorizedRole('admin'), updateUserRole)
router.delete('/admin/users/:id', auth, authorizedRole('admin'), deleteUser)

module.exports = router
