export const routePaths = {
    login: '/users/LogIn',
    signup: '/users/SignUp',
    allProducts : '/All/Products',
    category_items : '/Category/:name/Products',
    product_detail : '/Products/:id',
    searched_product : '/Products/search/:keyword',
    my_account : '/users/my-account',
    orders : '/users/my-account/orders',
    account_detail : '/users/my-account/account-details',
    addresses : '/users/my-account/manage-addresses',
    edit_details : '/users/my-account/edit-details',
    edit_address : '/users/my-account/edit-address',
    password_update : '/users/password/update',
    forget_password : '/users/forget/password',
    reset_password : '/password/reset/:token',
    mainCart : '/your/cart',
    checkout : '/checkout',
    order : '/order/:id',
    loggedinUserOrder : '/order/:name/:id',
    adminAccount : '/users/admin/my-account',
    createProduct : '/admin/create-product',
    createCategory : '/admin/create-category',
    adminAllProducts : '/admin/all/products',
    adminHome : '/admin',
    adminCategoryItems : '/admin/Category/:name/Products',
    admin_product_detail : '/admin/Products/:id',
    admin_update_product : '/admin/Products/update/:id',
    admin_all_orders : '/admin/all/orders',
    admin_single_order : '/admin/order/:id',
    admin_get_all_users : '/admin/all/users'
}