export const CREATE_NEWS_LETTER_REQUEST = 'CREATE_NEWS_LETTER_REQUEST'
export const CREATE_NEWS_LETTER_SUCCESS = 'CREATE_NEWS_LETTER_SUCCESS'
export const CREATE_NEWS_LETTER_FAILURE = 'CREATE_NEWS_LETTER_FAILURE'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
